# Generated by Django 2.2.1 on 2019-08-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusqa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAnswer',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
    ]
